
---
name: CI

on:
  push:
  schedule:
    - cron: "0 0 * * *" # daily

jobs:
  mypy:
    strategy:
      matrix:
        python_ver:
          - 3.8
          - 3.9
          - 3.8.2

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Pip Packages
        run: pip install -U mypy

      - name: Lint
        run: ./lint.sh

  tests:
    strategy:
      matrix:
        python_ver:
          - 3.9

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python_ver }}

      - name: Test
        run: sudo ./download.py

      # - name: Upload Artifacts
        # if: always()
        # uses: actions/upload-artifact@v2
        # with:
          # name: debug.zip
          # path: debug.zip
